version: "3.0"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: stick_db
      MYSQL_USER: ECE140B_styck
      MYSQL_PASSWORD: ECE140B_class
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
